### ISSUE TITLE
Support for Z-lift on retraction

### ISSUE THREAD

**Issue by kefir-** [dkobozev/tatlin#14]
Slicers have a feature to lift the Z axis on retraction, and then lower it again after the move has been made. Tatlin should detect such temporary lifts instead of calling creating a new "layer" for each move.

**Comment by dkobozev** [comment]
19ea82ba06770af6846623dbf70ab27e830d3338 improves layer separation and should fix this issue.

**Comment by kefir-** [comment]
Thanks! Look forward to testing.
