### ISSUE TITLE
Some ideas for gcode inspection

### ISSUE THREAD

**Issue by JohK** [dkobozev/tatlin#15]
Some ideas to facilitate the inspection of gcode: it would be nice to have the capability to load a stl and several gcodes at once.
##### User Interface:
- Could be tree like, similar to layers in GIMP or even similar to the data filter pipe in paraview
  (You have the base data i.e. the stl, and apply different "gcode filters" to it). A posibility to switch display  of each stl/gcode on and off individually as needed.
##### Display:
- A possibility to view a single layer of each gcode, and being able to link those between gcodes either by z-position or by layer count. So that you can scroll through the layers and inspect the difference between the two two.
- Stls should be displayed translucent.

**Comment by dkobozev** [comment]
Closed due to inactivity.
