### ISSUE TITLE
Please support some other extensions for gcode and other things..

### ISSUE THREAD

**Issue by onekk** [dkobozev/tatlin#21]
Hi, thaks for your great work, I've been searching a program like your for many time, please caould you support some other extensions for the gcode (like .nc or .ngc or .gc ) so a user is not forced to rename the file to load it.

I'm developing a gcode generator and your program let me to see the gcode generated, it will be very useful if a user can load a gcode and maybe the original stl to view the "rendered" gcode over the original image to evaluate the correctness of the path.

Many Thanks and Best Regards

Carlo D.

**Comment by onekk** [comment]
Re Hi, I wonder if i could use some of your code to obtain some data from the stl file, as example the dimensions and the boundingbox, but the relevant part of the code is buried in the ui initialization.
Could you kindly give me some info (or better) an example how to obtaining this data.
I'm writing this application: https://github.com/onekk/eurocam and usign the code for obtaining Gcode file from opencamlib.
I wonder if i could reuse some of your code (not the ui part as i use pyside / qt4) for obtaining the model data.

Many Thanks in advance.

Carlo D.

**Comment by dkobozev** [comment]
Hi Carlo,

I've added two options for opening gcode and stl files with any extension to the open file dialog.

You can take a look at libtatlin/stlparser.py and libtatlin/actors.py files to see the code that loads the stl and calculates the bounding box. The mechanism is very straighforward: read vertices from the stl file, use minimum and maximum vertex coordinates to calculate the bounding box.

**Comment by onekk** [comment]
Hi, many thanks for the answer, I have tried to use your code outside from tatlin but didn't get to obtain anything usable, maybe my poor knowledge of wxpython is blocking me, i'm stuck with the callback in many of the routines, could you help me a little?
I'm using Pyside (QT4) so I'm searching for a visualization engine and didn't find an usable, your software look promising, but it uses the wx engine.

Best Regards

carlo D.

**Comment by onekk** [comment]
Hi, I'm trying to obtain the boundigbox, how to pass from the stl file readed from this piece of code the object neede to the BoundingBox class to calculate the Counding box?

import sys

#from PySide import QtCore, QtGui

from libtatlin.stlparser import StlParser
from libtatlin.actors import BoundingBox

filename = "./stl/gnu_tux_mod.stl"

with open(filename, 'rb') as stl:
    parser = StlParser(stl)
    parser.load(stl)
    vertices, normals = parser.parse()

    print '[ OK   ] Parsed %d vertices' % len(vertices)

    print '[ INFO ] First vertices:'
    for vertex in vertices[:3]:
        print vertex
    print '[ INFO ] First normals:'
    for normal in normals[:3]:
        print normal

    print '[ INFO ] Last vertices:'
    for vertex in vertices[-3:]:
        print vertex
    print '[ INFO ] Last normals:'
    for normal in normals[-3:]:
        print normal


This code for extrancting the dimensions is correct ?

model = BoundingBox(object)

width = model.width
height = model.height
dept = model.depth

**Comment by onekk** [comment]
Hi, I've found the manner, thanks you and sorry for the bothering.

Regards

carlo D.
